version: '3.7'

services:
  backend-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - /app/src/node_modules
    container_name: backend-nodejs
    expose:
      - '5050'
    ports:
      - '5050:5050'
    depends_on:
      - postgres
    networks:
      - node-postgres

  postgres:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - '5432:5432'
    networks:
      - node-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
  
  pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - '5000:80'
    networks:
      - node-postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    
volumes:
  postgres-data:
    driver: local
  pgadmin:
    driver: local
networks:
  node-postgres: {}




    