version: '3.7'

services:
  backend-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - /app/src/node_modules
    container_name: backend-nodejs
    expose:
      - '5050'
    ports:
      - '5050:5050'
    depends_on:
      - postgres
    networks:
      - node-postgres

  postgres:
    image: postgres:12.11-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      APP_DB_USER: "${APP_DB_USER}"
      APP_DB_PASS: "${APP_DB_PASS}"
      APP_DB_NAME: "${APP_DB_NAME}"
    ports:
      - '5432:5432'
    networks:
      - node-postgres
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      - ./src/database/scripts/01createDatabase-init.sh:/docker-entrypoint-initdb.d/init-create-db.sh

  pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - '5000:80'
    networks:
      - node-postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    
volumes:
  postgres-data:
    driver: local
  pgadmin:
    driver: local
networks:
  node-postgres: {}




    